name: ServerSelectorX
main: xyz.derkades.serverselectorx.Main
version: '@project.version@'
author: Derkades
description: 'A modern server selector plugin'
website: 'https://www.spigotmc.org/resources/serverselectorx.32853/'
softdepend: [PlaceholderAPI]

commands:
  serverselectorx:
    aliases: [ss,ssx,serversel,serverselector]
    description: The one and only command of the ServerSelectorX plugin.
    usage: |-
      Aliases: serverselectorx, ss, ssx, serversel, serverselector
      
      /ssx reload/rl - Reload configuration files
      /ssx sync - Sync configuration files 